### ISSUE TITLE
Installs old version of dependencies

### ISSUE THREAD

**Issue by fleps** [qstar-inc/cities2-ElevatedTrainStation_VanillaSubway#2]
The mod doesn't detect that Asset Packs Manager and I18n are already installed on newer versions, and when using Skyve will forcibly install older versions of the mods, or complain about missing dependencies if we update the dependencies again.

Needs a fix to not have a specific version of a mod as dependency, just a minimal version and up.

**Comment by qstar-inc** [comment]
That's not a mod issue. Try unsub and resub.

**Comment by fleps** [comment]
> That's not a mod issue. Try unsub and resub.

Then it might be a Skyve issue? I apologize then.
